// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project03_CRUD_With_ASP.NET_MVC.Database;

namespace Project03_CRUD_With_ASP.NET_MVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210612144714_SecondMigration")]
    partial class SecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Project03_CRUD_With_ASP.NET_MVC.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("How")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("What")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("When")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Where")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Why")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
