// <auto-generated />
using ArtGalleryCRUD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArtGalleryCRUD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArtGalleryCRUD.Models.ArtistModel", b =>
                {
                    b.Property<int>("ArtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArtBio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ArtId = 1,
                            ArtBio = "Originally from a small town in the south of Italy Angelo Accardi moved to Napoli to study fine arts at the Art Academy of Naples. Shortly after, in the early 90s, he set up his personal studio close to his childhood home to embark on his pursuit of painting and sculpture. In the course of his artistic development, Accardi has been on a constant search for new sensations using mixed media to depictfigures against differing social backgrounds.",
                            ArtImg = "https://www.angeloaccardi.com/wp-content/uploads/sites/11/2017/12/acardi-620x620-home.jpg",
                            ArtName = "Angelo Accardi"
                        },
                        new
                        {
                            ArtId = 2,
                            ArtBio = "Trained and educated as an artist in the south of France, Benharrouche went on to become a distinguished professor of drawing and painting at Nice´s Academie Paganini. His influences include masters such as Chagall, Picasso, and Miro, yet Benharrouche’s personal style comes through in each of his compositions with much strength, balance and harmony. Deeply spiritual, Yoel Benharrouche establishes a sincere connection with his audience. His vibrant palette and mystical contemplation explore both the historical and spiritual world of Israel. He paints his surroundings with a lyrical quality that has landed him among the elite artists of the world, exploring the duality between the material and the mystical world.",
                            ArtImg = "https://www.eden-gallery.com/wp-content/uploads/sites/15/2017/09/yoel-benharrouche-at-the-studio-105-1-683x1024.jpg",
                            ArtName = "Benharrouche"
                        },
                        new
                        {
                            ArtId = 3,
                            ArtBio = "Born in California in 1965, Tommy studied art history at Santa Monica College in the United States, later on, studying architecture and interior design. His passion for aesthetics drove Tommy to dabble in different fields of design, like high-end furniture and silversmith work, eventually evolving into a painter and artist. Over the years, Tommy became an upscale interior designer, designing projects for high-end clientele.",
                            ArtImg = "https://d2vg5otv6yjmj3.cloudfront.net/wp-content/uploads/2015/12/tommy.jpg",
                            ArtName = "Tommy Shenkar"
                        });
                });

            modelBuilder.Entity("ArtGalleryCRUD.Models.BuyerModel", b =>
                {
                    b.Property<int>("ByrID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ByrMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ByrName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ByrPhone")
                        .HasColumnType("int");

                    b.HasKey("ByrID");

                    b.ToTable("Buyers");

                    b.HasData(
                        new
                        {
                            ByrID = 1,
                            ByrMail = "Jack@dns.com",
                            ByrName = "Jack",
                            ByrPhone = 9665964
                        },
                        new
                        {
                            ByrID = 2,
                            ByrMail = "mir@dns.com",
                            ByrName = "Mirry",
                            ByrPhone = 9345677
                        },
                        new
                        {
                            ByrID = 3,
                            ByrMail = "elsi@dns.com",
                            ByrName = "Elias",
                            ByrPhone = 4567899
                        },
                        new
                        {
                            ByrID = 4,
                            ByrMail = "ram@dns.com",
                            ByrName = "Ramii",
                            ByrPhone = 3456789
                        },
                        new
                        {
                            ByrID = 5,
                            ByrMail = "vic@dns.com",
                            ByrName = "vicku",
                            ByrPhone = 2345678
                        },
                        new
                        {
                            ByrID = 6,
                            ByrMail = "rs@dns.com",
                            ByrName = "rose",
                            ByrPhone = 3548765
                        });
                });

            modelBuilder.Entity("ArtGalleryCRUD.Models.GalleryModel", b =>
                {
                    b.Property<int>("GlrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GlrImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlrLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlrName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GlrId");

                    b.ToTable("Galleries");

                    b.HasData(
                        new
                        {
                            GlrId = 1,
                            GlrImg = "https://imgmediagumlet.lbb.in/media/2019/03/5c9b5aeac394967ce2d1f1f3_1553685226709.jpg?fm=webp&w=750&h=500&dpr=1",
                            GlrLocation = " Mumbai",
                            GlrName = "Volte"
                        },
                        new
                        {
                            GlrId = 2,
                            GlrImg = "https://imgmediagumlet.lbb.in/media/2019/04/5cbdad06b62ad10704e9f804_1555934470151.jpg?fm=webp&w=750&h=500&dpr=1",
                            GlrLocation = "London",
                            GlrName = "Gallery Chemould"
                        },
                        new
                        {
                            GlrId = 3,
                            GlrImg = "https://gulfbusiness.com/wp-content/uploads/2021/02/Website-Grosvenor-Gallery-London-Art-Dubai-Modern-March-20-Art-Dubai-2019-Courtesy-of-Photo-Solutions-3-1.jpg",
                            GlrLocation = "Dubai",
                            GlrName = "Art Dubai"
                        },
                        new
                        {
                            GlrId = 4,
                            GlrImg = "https://imgmediagumlet.lbb.in/media/2019/03/5c9b5aeac394967ce2d1f1f3_1553685226709.jpg?fm=webp&w=750&h=500&dpr=1",
                            GlrLocation = "Mumbai",
                            GlrName = "Volte2"
                        },
                        new
                        {
                            GlrId = 5,
                            GlrImg = "https://imgmediagumlet.lbb.in/media/2019/04/5cbdad06b62ad10704e9f804_1555934470151.jpg?fm=webp&w=750&h=500&dpr=1",
                            GlrLocation = "London",
                            GlrName = "Gallery Chemould2"
                        },
                        new
                        {
                            GlrId = 6,
                            GlrImg = "https://gulfbusiness.com/wp-content/uploads/2021/02/Website-Grosvenor-Gallery-London-Art-Dubai-Modern-March-20-Art-Dubai-2019-Courtesy-of-Photo-Solutions-3-1.jpg",
                            GlrLocation = "Dubai",
                            GlrName = "Art Dubai2"
                        },
                        new
                        {
                            GlrId = 7,
                            GlrImg = "https://imgmediagumlet.lbb.in/media/2019/03/5c9b5aeac394967ce2d1f1f3_1553685226709.jpg?fm=webp&w=750&h=500&dpr=1",
                            GlrLocation = "Mumbai",
                            GlrName = "Volte3"
                        },
                        new
                        {
                            GlrId = 8,
                            GlrImg = "https://imgmediagumlet.lbb.in/media/2019/04/5cbdad06b62ad10704e9f804_1555934470151.jpg?fm=webp&w=750&h=500&dpr=1",
                            GlrLocation = "London",
                            GlrName = "Gallery Chemould3"
                        },
                        new
                        {
                            GlrId = 9,
                            GlrImg = "https://gulfbusiness.com/wp-content/uploads/2021/02/Website-Grosvenor-Gallery-London-Art-Dubai-Modern-March-20-Art-Dubai-2019-Courtesy-of-Photo-Solutions-3-1.jpg",
                            GlrLocation = "Dubai",
                            GlrName = "Art Dubai3"
                        });
                });

            modelBuilder.Entity("ArtGalleryCRUD.Models.PaintingModel", b =>
                {
                    b.Property<int>("PntId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PntImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PntName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PntOverview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PntPrice")
                        .HasColumnType("float");

                    b.HasKey("PntId");

                    b.ToTable("Paintings");

                    b.HasData(
                        new
                        {
                            PntId = 1,
                            PntImg = "https://cdn.shopify.com/s/files/1/0436/1171/7792/products/AngeloAccardi-StandingTogether.1_1_1100x.jpg?v=1596095563",
                            PntName = "STANDING TOGETHER",
                            PntOverview = "3D Multilayered Papercut 108x143 cm | 42x56 in Limited Edition",
                            PntPrice = 10400.0
                        },
                        new
                        {
                            PntId = 2,
                            PntImg = "https://cdn.shopify.com/s/files/1/0436/1171/7792/products/AngeloAccardi-LookingDown.1_1_1100x.jpg?v=1606219907",
                            PntName = "LOOKING DOWN",
                            PntOverview = "3D Multilayered Papercut 80x100 cm | 31x39 in Limited Edition",
                            PntPrice = 8300.0
                        },
                        new
                        {
                            PntId = 3,
                            PntImg = "https://cdn.shopify.com/s/files/1/0436/1171/7792/products/AngeloAccardi-AbbeyRoad.1_860x.jpg?v=1596111743",
                            PntName = "ABBEY ROAD",
                            PntOverview = "3D Multilayered Papercut 56x75 cm | 22x29 in Limited Edition",
                            PntPrice = 5200.0
                        },
                        new
                        {
                            PntId = 4,
                            PntImg = "https://cdn.shopify.com/s/files/1/0436/1171/7792/products/Lescordesdemoname-2_1_1100x.jpg?v=1606229671",
                            PntName = "LES CORDES DE MON AME",
                            PntOverview = "Lacquer on metal 30x24 cm | 11x9 in Limited Editio",
                            PntPrice = 1600.0
                        },
                        new
                        {
                            PntId = 5,
                            PntImg = "https://cdn.shopify.com/s/files/1/0436/1171/7792/products/BouquetduParadis-2_1_1100x.jpg?v=1605538407",
                            PntName = "BOUQUET DU PARADIS",
                            PntOverview = "Lacquer on Metal 30x24 cm | 11x9 in Limited Edition",
                            PntPrice = 2600.0
                        },
                        new
                        {
                            PntId = 6,
                            PntImg = "https://cdn.shopify.com/s/files/1/0436/1171/7792/products/Sensiblecommelesfleurs-2_1_1100x.jpg?v=1606403544",
                            PntName = "SENSIBLE COMME LES FLEURS",
                            PntOverview = "Lacquer on metal 30x24 cm | 11x9 in Limited Editio",
                            PntPrice = 4600.0
                        },
                        new
                        {
                            PntId = 7,
                            PntImg = "https://cdn.shopify.com/s/files/1/0436/1171/7792/products/COVERGIRLMarilyn_1_1100x.jpg?v=1606836043",
                            PntName = "COVER GIRL MARILYN MONROE",
                            PntOverview = "Mixed Media Painting 120x76 cm | 47x29 in",
                            PntPrice = 5170.0
                        },
                        new
                        {
                            PntId = 8,
                            PntImg = "https://cdn.shopify.com/s/files/1/0436/1171/7792/products/JUSTAMOUSE__1_1100x.jpg?v=1606833970",
                            PntName = "JUST A MOUSE",
                            PntOverview = "Mixed Media Painting 40x67 cm | 15x26 in",
                            PntPrice = 5188.0
                        },
                        new
                        {
                            PntId = 9,
                            PntImg = "https://cdn.shopify.com/s/files/1/0436/1171/7792/products/THELASTSTAR__1_1100x.jpg?v=1606833845",
                            PntName = "THE LAST STAR",
                            PntOverview = "Mixed Media Painting 175x95 cm | 68x37 in",
                            PntPrice = 4600.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
