// <auto-generated />
using Hospital_project3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hospital_project3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hospital_project3.Models.AppointmentModel", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Date_Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("PhysicianId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PatientId");

                    b.HasIndex("PhysicianId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            ID = 772,
                            Date_Time = "10-12-2021 09:30AM",
                            PatientId = 1124398,
                            PhysicianId = 1110
                        },
                        new
                        {
                            ID = 733,
                            Date_Time = "03-09-2021 10:00AM",
                            PatientId = 1683398,
                            PhysicianId = 1113
                        },
                        new
                        {
                            ID = 992,
                            Date_Time = "09-02-2021 08:00AM",
                            PatientId = 1837354,
                            PhysicianId = 1119
                        },
                        new
                        {
                            ID = 338,
                            Date_Time = "11-07-2021 09:45AM",
                            PatientId = 1354922,
                            PhysicianId = 1180
                        },
                        new
                        {
                            ID = 334,
                            Date_Time = "30-05-2021 10:35AM",
                            PatientId = 1820336,
                            PhysicianId = 1151
                        },
                        new
                        {
                            ID = 177,
                            Date_Time = "20-11-2021 12:00PM",
                            PatientId = 1992755,
                            PhysicianId = 1180
                        },
                        new
                        {
                            ID = 886,
                            Date_Time = "19-10-2021 01:00PM",
                            PatientId = 1775342,
                            PhysicianId = 1111
                        });
                });

            modelBuilder.Entity("Hospital_project3.Models.DepartmentModel", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhysicianId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PhysicianId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            ID = 27,
                            Name = "Cardiology",
                            PhysicianId = 1113
                        },
                        new
                        {
                            ID = 66,
                            Name = "Internal medicine",
                            PhysicianId = 1111
                        },
                        new
                        {
                            ID = 90,
                            Name = "Anesthetics",
                            PhysicianId = 1151
                        },
                        new
                        {
                            ID = 44,
                            Name = "Emergency",
                            PhysicianId = 1113
                        },
                        new
                        {
                            ID = 20,
                            Name = "Neonatal",
                            PhysicianId = 1112
                        });
                });

            modelBuilder.Entity("Hospital_project3.Models.PatientModel", b =>
                {
                    b.Property<int>("NationalID")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NationalID");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            NationalID = 1122998,
                            Address = "Almoroj",
                            Gender = "Female",
                            Name = "Sara"
                        },
                        new
                        {
                            NationalID = 1124398,
                            Address = "Almoroj",
                            Gender = "Female",
                            Name = "Lama"
                        },
                        new
                        {
                            NationalID = 1683398,
                            Address = "Olia",
                            Gender = "Male",
                            Name = "Saud"
                        },
                        new
                        {
                            NationalID = 1992755,
                            Address = "Alworod",
                            Gender = "Male",
                            Name = "Fares"
                        },
                        new
                        {
                            NationalID = 1775342,
                            Address = "Alqadsiah",
                            Gender = "Male",
                            Name = "Battal"
                        },
                        new
                        {
                            NationalID = 1883547,
                            Address = "Narjes",
                            Gender = "Male",
                            Name = "Mohhamad"
                        },
                        new
                        {
                            NationalID = 1354922,
                            Address = "Qurtubah",
                            Gender = "Female",
                            Name = "Fai"
                        },
                        new
                        {
                            NationalID = 1820336,
                            Address = "Alsalman",
                            Gender = "Female",
                            Name = "Salwa"
                        },
                        new
                        {
                            NationalID = 1837354,
                            Address = "Alaziziah",
                            Gender = "Female",
                            Name = "Lamees"
                        });
                });

            modelBuilder.Entity("Hospital_project3.Models.PhysicianModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Physicians");

                    b.HasData(
                        new
                        {
                            Id = 1110,
                            Gender = "Male",
                            Name = "Hossam",
                            Position = "Pediatrician"
                        },
                        new
                        {
                            Id = 1111,
                            Gender = "Male",
                            Name = "Saad",
                            Position = "Internist"
                        },
                        new
                        {
                            Id = 1112,
                            Gender = "Male",
                            Name = "John",
                            Position = "Peadiatric neurologist"
                        },
                        new
                        {
                            Id = 1113,
                            Gender = "Female",
                            Name = "Eman",
                            Position = "Cardiologist"
                        },
                        new
                        {
                            Id = 1119,
                            Gender = "Female",
                            Name = "Sara",
                            Position = "Psychiatrist"
                        },
                        new
                        {
                            Id = 1117,
                            Gender = "Female",
                            Name = "Hana",
                            Position = "Surgeon"
                        },
                        new
                        {
                            Id = 1144,
                            Gender = "Male",
                            Name = "Jason",
                            Position = "Dermatologist"
                        },
                        new
                        {
                            Id = 1180,
                            Gender = "Female",
                            Name = "Abrar",
                            Position = "Internist"
                        },
                        new
                        {
                            Id = 1151,
                            Gender = "Male",
                            Name = "Derek",
                            Position = "Surgeon"
                        });
                });

            modelBuilder.Entity("Hospital_project3.Models.AppointmentModel", b =>
                {
                    b.HasOne("Hospital_project3.Models.PatientModel", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_project3.Models.PhysicianModel", "Physician")
                        .WithMany("appointments")
                        .HasForeignKey("PhysicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Physician");
                });

            modelBuilder.Entity("Hospital_project3.Models.DepartmentModel", b =>
                {
                    b.HasOne("Hospital_project3.Models.PhysicianModel", "Physician")
                        .WithMany("Departments")
                        .HasForeignKey("PhysicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Physician");
                });

            modelBuilder.Entity("Hospital_project3.Models.PatientModel", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Hospital_project3.Models.PhysicianModel", b =>
                {
                    b.Navigation("appointments");

                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
