// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using University_Project3_SSMS.Data;

namespace University_Project3_SSMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("University_Project3_SSMS.Models.CollegeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colleges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "FCIT"
                        },
                        new
                        {
                            Id = 2,
                            Name = "College of Engineering"
                        });
                });

            modelBuilder.Entity("University_Project3_SSMS.Models.InstructorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hasan",
                            PhoneNum = "0567800800"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ahmed",
                            PhoneNum = "0567800008"
                        });
                });

            modelBuilder.Entity("University_Project3_SSMS.Models.StudentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CollegeId = 1,
                            DateOfBirth = new DateTime(1991, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 1,
                            Major = "IS",
                            Name = "Hussain Abdullah Alghamdi",
                            PhoneNum = "0567800818"
                        },
                        new
                        {
                            Id = 2,
                            CollegeId = 1,
                            DateOfBirth = new DateTime(1995, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 2,
                            Major = "CS",
                            Name = "Thamer Saleh AlMthni",
                            PhoneNum = "0551609938"
                        });
                });

            modelBuilder.Entity("University_Project3_SSMS.Models.StudentModel", b =>
                {
                    b.HasOne("University_Project3_SSMS.Models.CollegeModel", "College")
                        .WithMany("Student")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_Project3_SSMS.Models.InstructorModel", "Instructor")
                        .WithMany("Student")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("College");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("University_Project3_SSMS.Models.CollegeModel", b =>
                {
                    b.Navigation("Student");
                });

            modelBuilder.Entity("University_Project3_SSMS.Models.InstructorModel", b =>
                {
                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
