// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupplierProject.Data;

namespace SupplierProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210612125527_addedData")]
    partial class addedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SupplierProject.Models.SupplierModel", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierID = 1,
                            Address = "Jubail",
                            FirstName = "Yasmin",
                            Gender = "Female",
                            LastName = "AlGhamdi",
                            PhoneNumber = "055-569-9110"
                        },
                        new
                        {
                            SupplierID = 2,
                            Address = "Dammam",
                            FirstName = "Rita",
                            Gender = "Female ",
                            LastName = "Farr",
                            PhoneNumber = "050-569-9110"
                        },
                        new
                        {
                            SupplierID = 3,
                            Address = "Riyadh",
                            FirstName = "Tony",
                            Gender = "Male",
                            LastName = "Roberts",
                            PhoneNumber = "054-932-6548"
                        },
                        new
                        {
                            SupplierID = 4,
                            Address = "Jeddah",
                            FirstName = "Amelia",
                            Gender = "Female",
                            LastName = "Owen",
                            PhoneNumber = "051-436-5094"
                        },
                        new
                        {
                            SupplierID = 5,
                            Address = "Dammam",
                            FirstName = "Kyle",
                            Gender = "Male ",
                            LastName = "Fox",
                            PhoneNumber = "059-330-4393"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
